
package com.company.test.ui;

import java.beans.Beans;

import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.RouterLink;
import com.vaadin.flow.server.VaadinService;


public class Second extends VerticalLayout
{

	/**
	 *
	 */
	public Second()
	{
		super();
		this.initUI();
	}

	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.verticalLayout = new VerticalLayout();
		this.routerLink     = new RouterLink();

		this.routerLink.setText("RouterLink");
		if(!Beans.isDesignTime())
		{
			this.routerLink.setRoute(VaadinService.getCurrent().getRouter(), MainLayout.class);
		}

		this.verticalLayout.add(this.routerLink);
		this.verticalLayout.setWidth("100px");
		this.verticalLayout.setHeight("100px");
		this.add(this.verticalLayout);
		this.setSizeFull();
	} // </generated-code>
	
	// <generated-code name="variables">
	private VerticalLayout verticalLayout;
	private RouterLink     routerLink;
	// </generated-code>
	
}
